version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: devops_class_db_user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Business@1
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: donald/devops-class:latest
    container_name: devops-class
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL:-jdbc:postgresql://postgres:5432/devops_db}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Business@1
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: